steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - hello_world
      - --region=europe-west3
      - --source=.
      - --trigger-http
      - --runtime=python39
      - --memory=128MB
      - --timeout=90
      - --min-instances=0
      - --max-instances=1
      - --security-level=secure-always
      - --ingress-settings=all
      - --no-allow-unauthenticated
      - --service-account=hello-world-function-sa@for-developers-343319.iam.gserviceaccount.com